kind: pipeline
type: docker
name: default

trigger:
  branch:
    - '16'
    - main
  event:
    - custom
    - push
    - pull_request

steps:
  # Build docker image
  - name: docker-build
    image: plugins/docker
    when:
      branch:
        - '16'
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - latest
        - '16'
        - '16.6'
  - name: docker-test
    image: kernel528/postgres:latest
    when:
      branch:
        - main
        - '16'
    commands:
      - cat /etc/alpine-release
      - uname -a
      - postgres --version
  - name: notify
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
    # template: >
    #  Drone build {{uppercase build.status}} for {{ build.link }} with git commit {{ truncate build.commit 8 }} to git branch ({{ build.branch }}) by {{ build.author }}.
    when:
      status:
        - failure
        - success