kind: pipeline
type: docker
name: postgres-image-build

trigger:
  branch:
    - '16-arm64'
    - 'main-arm64'
  event:
    - custom
    - push
    - pull_request

steps:
  - name: setup-qemu
    image: tonistiigi/binfmt
    privileged: true
    commands:
      - /bin/sh -c "echo 'Setting up QEMU for cross-platform builds'"

  - name: setup-buildx
    image: docker:24.0.2
    privileged: true
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  # Build docker image
  - name: docker-build
    image: plugins/docker
    when:
      branch:
        - '16-arm64'
      event:
        - push
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - '16-arm64'
        - '16-arm64-drone-build-${DRONE_BUILD_NUMBER}'
        - '16.8-arm64'
        - '16.8-arm64-drone-build-${DRONE_BUILD_NUMBER}'
        - 'latest-arm64'

  # Test docker image
  - name: docker-test
    image: kernel528/postgres:latest-arm64
    when:
      branch:
        - main-arm64
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - uname -a
      - postgres --version

  # Post slack notification
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
    when:
      status:
        - failure
        - success