kind: pipeline
type: docker
name: version-18

trigger:
  branch:
    - '18'
  event:
    - pull_request

# Build the docker image for the major version branch
steps:
  - name: v18-docker-image-build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - '18'
        - '18.0'
        - '18-drone-build-${DRONE_BUILD_NUMBER}'
        - '18.0-drone-build-${DRONE_BUILD_NUMBER}'
        - latest

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: main

trigger:
  event:
    - push
    - tag
  branch:
    - main

# Build the docker image for the main branch & tagged release
steps:
  - name: main-docker-image-build
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - ${DRONE_TAG}

  # Test docker image
  - name: latest-docker-test
    image: kernel528/postgres:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - uname -a
      - postgres --version

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts