kind: pipeline
type: docker
name: version-16

trigger:
  branch:
    - '16'
  event:
    - push

steps:
  - name: v16-docker-image-build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - '16'
        - '16.6'

---

kind: pipeline
type: docker
name: main

trigger:
  branch:
    - main
  event:
    - tag
    - push

steps:
  - name: main-docker-image-build
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - latest
        - ${DRONE_TAG}

  # Test docker image
  - name: latest-docker-test
    image: kernel528/postgres:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - uname -a
      - postgres --version

---

kind: pipeline
type: docker
name: slack-notification

steps:
  # Post slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts