kind: pipeline
type: docker
name: version-16

trigger:
  branch:
    - '16'
  event:
    - pull_request

steps:
  # Build the docker image for the major version
  - name: v16-docker-image-build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - '16'
        - '16.6'
        - latest

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: main

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: main-docker-image-build
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - ${DRONE_TAG}

  # Test docker image
  - name: latest-docker-test
    image: kernel528/postgres:latest
    when:
      branch:
        - main
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - uname -a
      - postgres --version

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts