pipeline:
  postgres-version:
    when:
      branch: master
      event: push
    image: kernel528/postgres:latest
    commands:
      - "cat /etc/alpine-release"
      - "postgres --version"

# Post notification to slack channel
  slack:
    when:
      status:
        - success
        - failure
      event:
        - push
        - tag
    image: plugins/slack
    channel: orpheus-alerts
    webhook: https://hooks.slack.com/services/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
    template: >
      Drone build {{uppercase build.status}} for {{ build.link }} with git commit {{ truncate build.commit 8 }} to git branch ({{ build.branch }}) by {{ build.author }}.
