kind: pipeline
type: docker
name: postgres-image-build

trigger:
  branch:
    - '16'
    - main
  event:
    - custom
    - push
    - pull_request

steps:
  # Build docker image
  - name: docker-build
    image: plugins/docker
    when:
      branch:
        - '16'
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/postgres
      tags:
        - latest
        - '16'
        - '16.6'

  # Test docker image
  - name: docker-test
    image: kernel528/postgres:latest
    when:
      branch:
        - main
        - '16'
    commands:
      - cat /etc/alpine-release
      - uname -a
      - postgres --version

  # Post slack notification
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - failure
        - success